[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "trading-bridge"
version = "0.0.1"
description = "실제 거래와 가상 거래를 위한 통합 브릿지 인터페이스"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "생선공장", email = "gatesplan@gmail.com"}
]
license = {text = "MIT"}
dependencies = []

[project.urls]
Homepage = "https://github.com/gatesplan/python-toolbox"
Repository = "https://github.com/gatesplan/python-toolbox"
